sudo: required
services:
  - docker

before_install:
  - docker build -t chuducty/d-r-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true chuducty/d-r-frontend npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "d-r-frontend"
  env: "DRFrontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-004834655703"
  bucket_path: "d-r-frontend"
  on:
    branch: master
  access_key_id: $AWS_BEANSTALK_ACCESS_KEY
  secret_access_key:
    secure: $AWS_BEANSTALK_SECRET_KEY